# AI 教材補充單元 - 矩陣運算介紹
- 2022 機器學習 Summer Session 教材 (師培中心)
- @ 台南應用科技大學 資管系 杜主民

## 一、單一個神經元 (Neuron)，有三個輸入神經元 X (input)  和權重 W (Weighting)

### 在尚未考量使用激勵函數(Activity Function)前提下，改寫上述方程式組為矩陣線性方程式:
$WX + B = S$

$W = \begin{bmatrix}
w_1 & w_2 & w_3 \end{bmatrix} \; ,$
$X = \begin{bmatrix}
x_1 \\
x_2 \\
x_3 \end{bmatrix} \; ,$
$B = \begin{bmatrix}
b \end{bmatrix} \; ,$
$S = \begin{bmatrix}
s \end{bmatrix}$

$\Rightarrow$
$\begin{bmatrix}
w_1 & w_2 &w_3 \end{bmatrix} $
$\begin{bmatrix}
x_1 \\
x_2 \\
x_3 \end{bmatrix}  + $
$\begin{bmatrix}
b \end{bmatrix} = $
$\begin{bmatrix}
s \end{bmatrix}$

$\Rightarrow$ 
$w_1x_1 + w_2x_2 + w_3x_3 + b = s$

In [2]:
# 練習題: 單一個神經元 (Neuron)，有三個輸入神經元 X (input) 和權重 W (Weighting)
import numpy as np

In [3]:
# 建立 1 個 weighting 矩陣
W = np.matrix(np.random.rand(1, 3))        # (1 x 3) 矩陣

# 建立 1 個 X 輸入神經元矩陣 (3 x 1)
X = np.matrix(np.random.randint(1, 11, 3)) # (1 x 3) 矩陣
X = X.T                                    # 轉換為 (3 x 1) 矩陣

# 建立 1 個 B Bias 矩陣 (1 x 1)
B = np.matrix('1.5')

In [4]:
print('W 權重型態: ', type(W))
print('X 輸入神經元型態: ', type(X))

W 權重型態:  <class 'numpy.matrix'>
X 輸入神經元型態:  <class 'numpy.matrix'>


In [6]:
print(f'W(權重)= {W.shape}')
print(f'X(神經元)= {X.shape}')
print(f'B(Bias) = {B.shape}')

W(權重)= (1, 3)
X(神經元)= (3, 1)
B(Bias) = (1, 1)


### WX + B = S
- W 維度 (1 x 3)
- X 維度 (3 x 1)
- B 維度 (1, 1)
- S 維度 (1, 1)

In [10]:
print(f'W: {W}')
print(f'X:\n {X}')
print(f'B: {B}')

W: [[0.95765284 0.27342092 0.11466286]]
X:
 [[6]
 [9]
 [7]]
B: [[1.5]]


In [7]:
S = W * X + B
print('S = ', S)

S =  [[9.95405741]]


## 二、兩個神經元 (Neuron)，有三個輸入神經元 X (input) 和權重 W (Weighting)

### 在尚未考量使用激活函數(Activity Function)前提下，改寫上述方程式組為矩陣線性方程式:
$WX + B = S$

$W = \begin{bmatrix}
w_{11} & w_{12} & w_{13} \\
w_{21} & w_{22} & w_{23}
\end{bmatrix} \; ,$
$X = \begin{bmatrix}
x_1 \\
x_2 \\
x_3 
\end{bmatrix} \; ,$
$B = \begin{bmatrix}
b_1 \\
b_2
\end{bmatrix} \; ,$
$S =\begin{bmatrix}
s_1 \\
s_2
\end{bmatrix}$

$\Rightarrow$
$\begin{bmatrix}
w_{11} & w_{12} & w_{13} \\
w_{21} & w_{22} & w_{23}
\end{bmatrix}$
$\begin{bmatrix}
x_1 \\
x_2 \\
x_3 
\end{bmatrix} + $
$\begin{bmatrix}
b_1 \\
b_2
\end{bmatrix} = $
$\begin{bmatrix}
s_1 \\
s_2
\end{bmatrix}$
$\Rightarrow$

$w_{11}x_1 + w_{12}x_2 + w_{13}x_3 + b_1 = s_1$ <p>
$w_{21}x_1 + w_{22}x_2 + w_{23}x_3 + b_2 = s_2$ <p>

In [11]:
# 二個神經元 (Neuron)，有三個輸入神經元 X (input) 和權重 W (Weighting)
import numpy as np

In [12]:
# 建立 1 個 weighting 矩陣
W = np.matrix(np.random.rand(2, 3))        # (2 x 3) 矩陣

# 建立 1 個 X 輸入神經元矩陣矩陣 (3 x 1)
X = np.matrix(np.random.randint(1, 11, 3)) # (1 x 3 ) 矩陣
X = X.T                                    # 轉換為 (3 x 1) 矩陣

# 建立 1 個 B Bias矩陣 (2 x 1)
B = np.matrix('1.5; 2.1')

In [13]:
print('W(權重) = \n', W.shape)
print('X(神經元) = \n', X.shape)
print('B(Bias) = \n', B)

W(權重) = 
 (2, 3)
X(神經元) = 
 (3, 1)
B(Bias) = 
 [[1.5]
 [2.1]]


### WX + B = S
- W 維度 (2 x 3)
- X 維度 (3 x 1)
- B 維度 (2, 1)
- S 維度 (2, 1)

In [15]:
print(f'W:\n {W}')
print(f'X:\n {X}')
print(f'B: {B}')

W:
 [[0.90368401 0.96455174 0.52995099]
 [0.35731436 0.25832049 0.71797357]]
X:
 [[ 7]
 [ 2]
 [10]]
B: [[1.5]
 [2.1]]


In [16]:
S = W * X + B
print('S = \n', S)

S = 
 [[15.05440143]
 [12.29757717]]


## 三、m 個神經元 (Neuron)，有 n 個輸入神經元 X (input) 和權重 W (Weighting)

### 在尚未考量使用激勵函數(Activity Function)前提下，
### 將上述方程式組改寫成矩陣的線性方程式寫法:
$WX + B = S$

$ W = $
$\begin{bmatrix}
w_{11} & w_{12} & \cdots & w_{1n} \\
w_{21} & w_{22} & \cdots & w_{2n} \\
\; \ddots \\
w_{m1} & w_{m2} & \cdots & w_{mn} 
\end{bmatrix}$
$ \; \;X = $
$\begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{bmatrix}$
$ \; \; B = $
$\begin{bmatrix}
b_1 \\
b_2 \\
\vdots \\
b_m
\end{bmatrix}$
$ \; \; S = $
$\begin{bmatrix}
s_1 \\
s_2 \\
\vdots \\
s_m
\end{bmatrix}$

$\Rightarrow$
$\begin{bmatrix}
w_{11} & w_{12} & \cdots & w_{1n} \\
w_{21} & w_{22} & \cdots & w_{2n} \\
\; \ddots \\
w_{m1} & w_{m2} & \cdots & w_{mn} 
\end{bmatrix}$
$\begin{bmatrix}
x_1 \\
x_2 \\
\vdots \\
x_n
\end{bmatrix} + $
$\begin{bmatrix}
b_1 \\
b_2 \\
\vdots \\
b_m
\end{bmatrix} = $
$\begin{bmatrix}
s_1 \\
s_2 \\
\vdots \\
s_m
\end{bmatrix}$

$\Rightarrow$

$w_{11}x_1 + w_{12}x_2 + \cdots + w_{1n}x_n + b_1 = s_1$ <p>
$w_{21}x_1 + w_{22}x_2 + \cdots + w_{2n}x_n + b_2 = s_2$ <p>
$\; \ddots$ <p>
$w_{m1}x_1 + w_{m2}x_2 + \cdots + w_{mn}x_n + b_m = s_m$ <p>

In [17]:
# 練習題: m 個 Neuron，n 個輸入 x 和權重 (Weighting) w
# 假設有 10 個 Neuron，100 個輸入 x 
import numpy as np

In [18]:
# 建立 1 個 weighting 矩陣 (10, 100)
W = np.matrix(np.random.rand(10, 100))         # (10 x 100) 矩陣

# 建立 1 個 X 輸入神經元矩陣矩陣  (100 x 1)
X = np.matrix(np.random.randint(-10, 10, 100)) # (1 x 100 ) 矩陣
X = X.T                                        # 轉換為 (100 x 1) 矩陣

# 建立 1 個 B Bias 矩陣 (10 x 1)
# 在 1-20  間隨機取 10 個整數當成 bias 矩陣，預設是 (1 x 10)
B = np.matrix(np.random.randint(1, 21, 10)) 
B = B.T                                        # 轉換為 (10 x 1) 矩陣

In [22]:
print('W(權重) = \n', W.shape)
print('X(神經元) = \n', X.shape)
print('B(Bias) = \n', B.shape)

W(權重) = 
 (10, 100)
X(神經元) = 
 (100, 1)
B(Bias) = 
 (10, 1)


### WX + B = S
- W 維度 (m x n)
- X 維度 (n x 1)
- B 維度 (m, 1)
- S 維度 (m, 1)

In [ ]:
print(f'W:\n {W}')
print(f'X:\n {X}')
print(f'B: {B}')

In [20]:
S = W * X + B
print('S =\n', S)

S =
 [[15.78310694]
 [-1.81328526]
 [51.12892224]
 [36.01678674]
 [ 2.46798174]
 [34.92068064]
 [19.78249941]
 [ 5.50576299]
 [14.67629109]
 [39.27265126]]
